AllCops:
  EnabledByDefault: true
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"
    - "Gemfile"
    - 'spec/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    
  DisplayCopNames: true
Layout/LineLength:
  Max: 142
Metrics/MethodLength:
  Max: 22
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ["describe"]
  Max: 50

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/AssignmentInCondition:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
